// <auto-generated />
namespace TD.QLDC.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "7.1.0.0")]
    public sealed partial class create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create));
        
        string IMigrationMetadata.Id
        {
            get { return "202001131125431_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
