// <auto-generated />
namespace TD.QLDC.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "7.1.0.0")]
    public sealed partial class update1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update1));
        
        string IMigrationMetadata.Id
        {
            get { return "202112100209485_update1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
